url: https://oshomo.oforomeh.com
baseurl:
title: Oshomo Oforomeh
subtitle: Personal website and articles.
author: Oshomo Oforomeh
simple_search: http://google.com/search
description: Oshomo Oforomeh personal website and articles.
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:year/:month/:title
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
jekyll_compose:
  default_front_matter:
    drafts:
      layout: post
      categories:
    posts:
      layout: post
      categories:
